plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testImplementation 'io.swagger.parser.v3:swagger-parser:2.1.48'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

test {
    useJUnitPlatform()
}

tasks.register('docletPath', Sync) {
    dependsOn jar
    from jar
    from configurations.runtimeClasspath
    into layout.buildDirectory.dir('doclet')
}
