[versions]
mixinExtras = "0.5.0-rc.3"
ae2 = "15.4.10"
emi = "1.1.13+1.20.1"

## modrinth maven ##
jade = "11.6.3"
embeddium = "0.3.31+mc1.20.1"
oculus = "1.20.1-1.8.0"
modernfix = "DdUByV9S" # 5.24.1+mc1.20.1
guideme = "20.1.7"

## cursemaven ##
ae2wtlib = "5217955"
spark = "4738952"
advancedae = "7939754"

[libraries]
mixinExtras-common  = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinExtras" }
mixinExtras-forge   = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinExtras" }
ae2                 = { module = "appeng:appliedenergistics2-forge", version.ref = "ae2" }
ae2wtlib            = { module = "curse.maven:ae2wtlib-459929", version.ref = "ae2wtlib" }
advancedae          = { module = "curse.maven:advancedae-1084104", version.ref = "advancedae" }
emi                 = { module = "dev.emi:emi-forge", version.ref = "emi" }
jade                = { module = "maven.modrinth:jade", version.ref = "jade" }
embeddium           = { module = "maven.modrinth:embeddium", version.ref = "embeddium" }
oculus              = { module = "maven.modrinth:oculus", version.ref = "oculus" }
modernfix           = { module = "maven.modrinth:modernfix", version.ref = "modernfix" }
guideme             = { module = "org.appliedenergistics:guideme", version.ref = "guideme" }
spark               = { module = "curse.maven:spark-361579", version.ref = "spark" }
