modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "ae2webintegration"
version = "${version}"
displayName = "AE2WebIntegration"
authors = "kuba6000"
description = "${mod_description}"
logoFile = ""
displayURL = "${mod_url}"
credits = ""

[[dependencies.ae2webintegration]]
modId = "ae2"
mandatory = true
versionRange = "[15.1.0,)"
