
name: Build and test

on:
  pull_request:
    branches: [ 1.20.1 ]
  push:
    branches: [ 1.20.1 ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
    with:
      timeout: 150
