name: Test Scala Presence

on:
  pull_request:
    branches: [ 1.20.1 ]
  push:
    branches: [ 1.20.1 ]

jobs:
  test-scala-presence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check file content
        uses: mattsb42-meta/not-grep@1.0.0
        with:
          config-file: ./.github/test-scala-presence.toml
